# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mvglm',
                'doc_host': 'https://jackhogan.github.io',
                'git_url': 'https://github.com/jackhogan/mvglm',
                'lib_path': 'mvglm'},
  'syms': {'mvglm.core': {'mvglm.core.foo': ('core.html#foo', 'mvglm/core.py')}}}
